# TODO: extend so it takes several languages and I can just provide the country
paths:
  texts: "parla-parla\\dataset\\ParlaMint-IT-en.txt"
  conllu: "parla-parla\\dataset\\ParlaMint-IT-en.conllu"
  preprocessed_data: "parla-parla\\assets\\parlamint_df.parquet"

# Flag to load preprocessed, False if want to load from scratch and apply certain filters on data
load_preprocessed: True

llm:
  model: "FacebookAI/roberta-base"

# training settings
training:
  model_type: "custom" # custom or pretrained.
  seed: 42
  batch_size: 8
  lr: 1e-3
  epochs: 3
  weight_decay: 0.01
  unfreeze: False
  use_lora: False
  classifier:
    hidden_dim: 256
    dropout: 0.1

# parameters for optuna for training trials
# if not using optuna this won't affect at all
optuna:
  batch_size: [8, 16, 32]
  lr:
    min: 1e-5
    max: 1e-3
  weight_decay:
    min: 1e-5
    max: 1e-2
  classifier:
    hidden_dim: [124, 256, 512, 1024]

# Dataset configuration, thresholds and parameters for preprocessing
dataset:
  # Specifies which column the DatasetPipeline should use as the target label
  # during filtering, undersampling, and dataset splitting.
  target_column: "Party_orientation"
  word_count:
    min: 5
    max: 70
  sampling:
    enabled: True
    max_samples: 10

# FILTERS
# Add filters to remove data from being processed. Leave filter emtpy to process everything
# NOTE: - For topics and orientations to filter - set it as a string '-'
#       - For years set as strings '2013'

# Topics filter

# Possible topics:
# Macroeconomics, Health, Mix, Law and Crime, Culture, Other
# Agriculture, Technology, Energy, Government Operations, Environment
# Transportation, International Affairs, Domestic Commerce, Foreign Trade
# Public Lands, Social Welfare, Civil Rights, Labor
# Immigration, Housing, Defense, Education, -
topics:
  # Example:
  #- Health

# Orientations filter

# Possible party orientations:
# Centre-right, Left, Centre, Centre to centre-left
# Centre-left, Right to far-right, Big tent, -
orientations:

# Years filter

# dataset goes from 2013-2022
years:
